default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: rails_blog_dev
  password:

test: &test
  <<: *default
  database: rails_blog_test

production:
  <<: *default
  database: rails_blog